// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1elnMEWFelH0GPzFYX9L3Q2UdcEQVqY',
    appId: '1:916517402300:web:e7fd94929fb56f25a642b9',
    messagingSenderId: '916517402300',
    projectId: 'mini-grocery-store',
    authDomain: 'mini-grocery-store.firebaseapp.com',
    storageBucket: 'mini-grocery-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkyQQO-pu1eHGT1NDg0Qe-OpK8NCwpxY',
    appId: '1:916517402300:android:7d5b0a1e337daf40a642b9',
    messagingSenderId: '916517402300',
    projectId: 'mini-grocery-store',
    storageBucket: 'mini-grocery-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBKyWCCtPGXRXi96AY0vfq81dxLA3KYk',
    appId: '1:916517402300:ios:f4c118629b3ff1b6a642b9',
    messagingSenderId: '916517402300',
    projectId: 'mini-grocery-store',
    storageBucket: 'mini-grocery-store.appspot.com',
    iosBundleId: 'com.example.miniGroceryStore',
  );
}
